project:
 type: website

website:
 draft-mode: visible
 title: "iSRL"
 navbar:
  pinned: true
  right:
   - href: index.qmd
     text: Home
   - href: roadmap.qmd
     text: Roadmap
   - href: join-us.qmd
     text: Join us
   - href: fund.qmd
     text: Funding
   - href: pub/index.qmd
     text: Publications
   - href: https://zenodo.org/communities/isrl/records
     text: Zenodo
   - href: team/index.qmd
     text: Team
   - about.qmd


format:
 html:
  theme:
   - litera
   - brand
   - custom.scss
  css: styles.css
  toc: true
  fontsize: 17px
  backgroundcolor: '#f7f6f2'
  filters: 
    - highlight-span.lua
  reference-location: margin